[devshell]
packages = [
  "alejandra", # Formatter for nix
  "deno",
  "taplo-cli",
]

[[commands]]
package = "treefmt"
category = "formatter"

[[commands]]
name = "update_lockfile"
command = "deno cache --import-map=./import_map.json --lock lock.json --lock-write ./mod.ts"
